[build-system]
requires = ["ppsetuptools", "wheel"]

[project]
name = "pwcp"
description = "Python with C preprocessor"
dependencies = ["pypp@git+https://github.com/Krutyi-4el/pypp.git@7eca11e9073120959f131b11b3c800417a0049b6"]
optional-dependencies = {tests = ["pytest"]}
dynamic = ["version"]
scripts = {pwcp = "pwcp:main"}

[tool.setuptools]
packages = ["pwcp"]

[tool.setuptools.dynamic]
version = {attr = "pwcp.version.__version__"}
